#!/usr/bin/env bash
# Generates $APPLICANT_DIR/memory/applicant-setup-status.md from authoritative sources.
# Runs automatically from the Stop hook after every Claude response.
# Fails silently so it never blocks the hook chain.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)" || exit 0
ENV_FILE="$REPO_ROOT/.env"
[ -f "$ENV_FILE" ] && source "$ENV_FILE" || exit 0
[ -z "${APPLICANT_DIR:-}" ] && exit 0

TRACKER="$APPLICANT_DIR/application-tracker.md"
PROFILES_DIR="$APPLICANT_DIR/profiles"
STATUS_FILE="$APPLICANT_DIR/memory/applicant-setup-status.md"
TIMESTAMP="$(date '+%Y-%m-%d %H:%M')"

# ── Active profiles (subdirectories only, excluding utility items) ──────────
ACTIVE_PROFILES=""
if [ -d "$PROFILES_DIR" ]; then
  while IFS= read -r d; do
    name="$(basename "$d")"
    case "$name" in
      PROFILES-QUICK-REFERENCE*|EXPERIENCE-REFERENCE*|search-results*) ;;
      *) ACTIVE_PROFILES+="- $name"$'\n' ;;
    esac
  done < <(find "$PROFILES_DIR" -maxdepth 1 -mindepth 1 -type d | sort)
fi
[ -z "$ACTIVE_PROFILES" ] && ACTIVE_PROFILES="(none found)"

# ── Pipeline counts ─────────────────────────────────────────────────────────
ACTIVE_COUNT=0; PENDING_COUNT=0; TOTAL_COUNT=0
if [ -f "$TRACKER" ]; then
  TOTAL_COUNT=$(grep -c '^| 20' "$TRACKER" 2>/dev/null || true)
  PENDING_COUNT=$(grep '^| 20' "$TRACKER" 2>/dev/null | grep -c 'pending review' || true)
  ACTIVE_COUNT=$(( TOTAL_COUNT - PENDING_COUNT ))
fi

# ── High-priority active applications ───────────────────────────────────────
HOT_ITEMS=""
if [ -f "$TRACKER" ]; then
  while IFS= read -r line; do
    case "$line" in
      *Rejected*|*Closed*) ;;
      *) HOT_ITEMS+="$line"$'\n' ;;
    esac
  done < <(grep '^| 20' "$TRACKER" 2>/dev/null | grep '⭐️⭐️⭐️' || true)
fi
[ -z "$HOT_ITEMS" ] && HOT_ITEMS="(none)"

# ── Next follow-up date ──────────────────────────────────────────────────────
NEXT_FOLLOWUP="(none scheduled)"
if [ -f "$TRACKER" ]; then
  NEXT_FOLLOWUP=$(grep -o 'Follow up [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}' "$TRACKER" 2>/dev/null \
    | grep -o '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}' \
    | sort \
    | awk -v today="$(date '+%Y-%m-%d')" '$0 >= today {print; exit}' \
    || true)
  [ -z "$NEXT_FOLLOWUP" ] && NEXT_FOLLOWUP="(none scheduled)"
fi

# ── Unverified items ─────────────────────────────────────────────────────────
UNVERIFIED=""
if [ -d "$PROFILES_DIR" ]; then
  UNVERIFIED=$(grep -r '\[UNVERIFIED\]' "$PROFILES_DIR" 2>/dev/null \
    | grep -v 'must be confirmed before use\|All facts verified' \
    | sed 's|'"$PROFILES_DIR/"'||' \
    | head -20 \
    || true)
fi
[ -z "$UNVERIFIED" ] && UNVERIFIED="None found"

# ── Write status file ────────────────────────────────────────────────────────
mkdir -p "$(dirname "$STATUS_FILE")"
cat > "$STATUS_FILE" <<EOF
# Applicant Setup Status
_Auto-generated by Stop hook — ${TIMESTAMP}_

## Setup Phases
- Phase A–E (initial setup): Complete
- Phase F (ongoing maintenance): Active

## Active Profiles
${ACTIVE_PROFILES}
## Pipeline Summary
Active: ${ACTIVE_COUNT}  |  Pending review: ${PENDING_COUNT}  |  Total tracked: ${TOTAL_COUNT}

## High-Priority Active Applications (⭐️⭐️⭐️)
${HOT_ITEMS}
## Next Follow-Up
${NEXT_FOLLOWUP}

## Unverified Items
${UNVERIFIED}
EOF
